"""added cover image to album

Revision ID: 18436d0589d6
Revises: baa20608df97
Create Date: 2024-03-16 15:42:23.720426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18436d0589d6'
down_revision = 'baa20608df97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_played', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_column('time_played')

    # ### end Alembic commands ###
