"""remove fk from fs

Revision ID: 33158bbb72a7
Revises: 4337d90cb0e5
Create Date: 2024-03-31 17:57:33.474193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33158bbb72a7'
down_revision = '4337d90cb0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flaggedsongs', schema=None) as batch_op:
        batch_op.alter_column('song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('soid', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flaggedsongs', schema=None) as batch_op:
        batch_op.create_foreign_key('soid', 'song', ['song_id'], ['id'])
        batch_op.alter_column('song_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
