"""added plays

Revision ID: 7c09636eb885
Revises: 1174c92565f1
Create Date: 2024-03-29 16:12:07.848712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c09636eb885'
down_revision = '1174c92565f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plays', sa.Integer(), nullable=True))
        batch_op.drop_column('time_played')

    with op.batch_alter_table('cycledata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plays', sa.Integer(), nullable=True))
        batch_op.drop_column('likes')
        batch_op.drop_column('time_played')

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plays', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plays', sa.Integer(), nullable=True))
        batch_op.drop_column('cflags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cflags', sa.INTEGER(), nullable=True))
        batch_op.drop_column('plays')

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('plays')

    with op.batch_alter_table('cycledata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_played', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=False))
        batch_op.drop_column('plays')

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_played', sa.INTEGER(), nullable=False))
        batch_op.drop_column('plays')

    # ### end Alembic commands ###
