"""modified data cycle

Revision ID: 82f00d62270d
Revises: 014f07404d63
Create Date: 2024-03-28 18:24:56.953007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f00d62270d'
down_revision = '014f07404d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycledata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.alter_column('time_played',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('sid', type_='foreignkey')
        batch_op.drop_column('song_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycledata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('sid', 'song', ['song_id'], ['id'])
        batch_op.alter_column('time_played',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('item_id')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
