"""changed pic to audio

Revision ID: fd0a368e6f1e
Revises: a594aaa2898f
Create Date: 2024-03-15 22:02:08.811742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0a368e6f1e'
down_revision = 'a594aaa2898f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(length=255), nullable=True))
        batch_op.drop_column('pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('cover')

    # ### end Alembic commands ###
